(() => {
  'use strict'

  const STORAGE = {
    state: 'daily-planner-state-v1',
    credentials: 'daily-planner-credentials-v1',
    cache: 'daily-planner-cloud-cache-v1',
    pending: 'daily-planner-sync-pending-v1',
  }
  const DEFAULT_SETTINGS = { focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15, longBreakInterval: 4 }
  const state = { tasks: [], pomodoroLog: [], settings: { ...DEFAULT_SETTINGS }, filter: 'all', sort: 'urgency', sync: { token: '', gistId: '', status: 'local', message: '' } }
  let syncTimer = null
  let toastTimer = null
  const timer = { running: false, phase: 'focus', remaining: 0, total: 0, completedFocuses: 0, boundTaskId: '', interval: null, startedAt: null }

  const $ = (selector) => document.querySelector(selector)
  const $$ = (selector) => [...document.querySelectorAll(selector)]
  const safeId = () => (globalThis.crypto?.randomUUID ? crypto.randomUUID() : `task-${Date.now()}-${Math.random().toString(16).slice(2)}`)
  const todayDate = () => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), now.getDate()) }
  const dateOnly = (value) => { if (!value) return null; const [y, m, d] = value.split('-').map(Number); return new Date(y, m - 1, d) }
  const dayDiff = (later, earlier) => Math.round((later - earlier) / 86400000)
  const isoDate = (date) => { const y = date.getFullYear(); const m = `${date.getMonth() + 1}`.padStart(2, '0'); const d = `${date.getDate()}`.padStart(2, '0'); return `${y}-${m}-${d}` }
  const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]))
  const formatDate = (value) => { const date = dateOnly(value); return date ? date.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' }) : '' }
  const formatDateTime = (value) => new Date(value).toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })

  function showToast(message, type = '') {
    const region = $('#toastRegion')
    if (!region) return
    const toast = document.createElement('div')
    toast.className = `toast ${type}`.trim()
    toast.textContent = message
    region.appendChild(toast)
    clearTimeout(toastTimer)
    toastTimer = setTimeout(() => toast.remove(), 3600)
  }

  function loadState() {
    try {
      const saved = JSON.parse(localStorage.getItem(STORAGE.state) || '{}')
      if (Array.isArray(saved.tasks)) state.tasks = saved.tasks.map(normalizeTask)
      if (Array.isArray(saved.pomodoroLog)) state.pomodoroLog = saved.pomodoroLog
      if (saved.settings) state.settings = { ...DEFAULT_SETTINGS, ...saved.settings }
      const credentials = JSON.parse(localStorage.getItem(STORAGE.credentials) || '{}')
      state.sync.token = credentials.token || ''
      state.sync.gistId = credentials.gistId || ''
      if (state.sync.token && state.sync.gistId) state.sync.status = 'pending'
      const cached = JSON.parse(localStorage.getItem(STORAGE.cache) || 'null')
      if (!state.tasks.length && cached?.tasks) state.tasks = cached.tasks.map(normalizeTask)
      if (!state.pomodoroLog.length && cached?.pomodoroLog) state.pomodoroLog = cached.pomodoroLog
    } catch (error) { showToast('本地缓存读取失败，已使用空白数据。', 'error') }
  }

  function normalizeTask(task) { const legacyPriority = { high: 'daily', medium: 'weekly', low: 'longterm' }[task.priority]; const tags = Array.isArray(task.tags) ? [...new Set(task.tags.filter((tag) => ['test', 'optimization'].includes(tag)))] : []; const review = task.review && typeof task.review === 'object' ? { clientName: task.review.clientName || '', action: task.review.action || '', result: task.review.result || '', updatedAt: task.review.updatedAt || undefined } : undefined; return { id: task.id || safeId(), title: String(task.title || '').trim(), notes: task.notes || '', priority: ['daily', 'weekly', 'longterm'].includes(task.priority) ? task.priority : (legacyPriority || 'weekly'), deadline: task.deadline || '', status: ['todo', 'doing', 'waiting', 'done'].includes(task.status) ? task.status : 'todo', createdAt: task.createdAt || new Date().toISOString(), waitingAt: task.waitingAt || undefined, doneAt: task.doneAt || undefined, pomodoroCount: Number(task.pomodoroCount) || 0, focusMinutes: Number(task.focusMinutes) || 0, tags, review } }
  function saveLocal() { localStorage.setItem(STORAGE.state, JSON.stringify({ tasks: state.tasks, pomodoroLog: state.pomodoroLog, settings: state.settings })); localStorage.setItem(STORAGE.credentials, JSON.stringify({ token: state.sync.token, gistId: state.sync.gistId })) }
  function saveCloudCache() { localStorage.setItem(STORAGE.cache, JSON.stringify({ tasks: state.tasks, pomodoroLog: state.pomodoroLog, savedAt: new Date().toISOString() })) }
  function persist({ sync = true } = {}) { saveLocal(); render(); if (sync) scheduleSync() }

  function urgencyInfo(task) {
    const ageDays = Math.max(0, dayDiff(todayDate(), new Date(new Date(task.createdAt).getFullYear(), new Date(task.createdAt).getMonth(), new Date(task.createdAt).getDate())))
    let daysLeft = null; let deadlineUrgency = 0
    if (task.deadline) { daysLeft = dayDiff(dateOnly(task.deadline), todayDate()); if (daysLeft < 0) deadlineUrgency = 1000 + Math.abs(daysLeft) * 10; else if (daysLeft === 0) deadlineUrgency = 900; else if (daysLeft === 1) deadlineUrgency = 850; else if (daysLeft <= 3) deadlineUrgency = 700; else if (daysLeft <= 7) deadlineUrgency = 550; else if (daysLeft <= 14) deadlineUrgency = 400; else deadlineUrgency = 200 }
    const promotedWeekly = task.priority === 'weekly' && ageDays > 2
    return { daysLeft, ageDays, promotedWeekly, score: deadlineUrgency + Math.min(ageDays * 8, 300) }
  }

  // 智能排序层级：逾期 > 创建超过 2 天的本周任务 > 当日任务 > 本周任务 > 长期任务。
  function smartSortRank(task, info = urgencyInfo(task)) {
    if (info.daysLeft !== null && info.daysLeft < 0) return 0
    if (info.promotedWeekly) return 1
    if (task.priority === 'daily' || info.daysLeft === 0) return 2
    if (task.priority === 'weekly') return 3
    return 4
  }

  function taskComparator(a, b) {
    if (state.sort === 'created') return new Date(a.createdAt) - new Date(b.createdAt)
    if (state.sort === 'deadline') { if (!a.deadline && !b.deadline) return new Date(a.createdAt) - new Date(b.createdAt); if (!a.deadline) return 1; if (!b.deadline) return -1; return dateOnly(a.deadline) - dateOnly(b.deadline) || new Date(a.createdAt) - new Date(b.createdAt) }
    const aInfo = urgencyInfo(a); const bInfo = urgencyInfo(b)
    const rankDiff = smartSortRank(a, aInfo) - smartSortRank(b, bInfo)
    if (rankDiff) return rankDiff
    const scoreDiff = bInfo.score - aInfo.score
    return scoreDiff || new Date(a.createdAt) - new Date(b.createdAt)
  }

  function visibleTasks() { return state.tasks.filter((task) => task.status !== 'done' && (state.filter === 'all' || state.filter === task.status)).sort(taskComparator) }
  function deadlineBadge(task) { if (!task.deadline) return ''; const { daysLeft } = urgencyInfo(task); let label = formatDate(task.deadline); let klass = ''; if (daysLeft < 0) { label = `已逾期 ${Math.abs(daysLeft)} 天`; klass = 'overdue' } else if (daysLeft === 0) { label = '今天到期'; klass = 'soon' } else if (daysLeft === 1) { label = '明天到期'; klass = 'soon' } else if (daysLeft <= 3) { label = `${daysLeft} 天后到期`; klass = 'near' } return `<span class="badge deadline ${klass}">◷ ${label}</span>` }
  function staleBadge(task) { const { ageDays } = urgencyInfo(task); if (ageDays < 4) return ''; if (ageDays <= 7) return `<span class="badge stale mild">⌛ 已放置 ${ageDays} 天</span>`; if (ageDays < 14) return `<span class="badge stale warn">⌛ 已放置 ${ageDays} 天</span>`; return `<span class="badge stale critical">⚠ 已拖延超过两周</span>` }
  function promotionBadge(task) { const { promotedWeekly } = urgencyInfo(task); return promotedWeekly ? '<span class="badge promoted">↑ 本周任务已自动提升至今日首位</span>' : '' }
  function waitingBadge(task) { if (task.status !== 'waiting') return ''; const waitingAt = task.waitingAt ? new Date(task.waitingAt) : new Date(); const waitingDay = new Date(waitingAt.getFullYear(), waitingAt.getMonth(), waitingAt.getDate()); const days = Math.max(0, dayDiff(todayDate(), waitingDay)); const label = days === 0 ? '今天进入待回复' : `已等待客户 ${days} 天`; const level = days >= 7 ? 'critical' : days >= 3 ? 'warn' : 'mild'; return `<span class="badge waiting ${level}">↗ ${label}</span>` }
  function priorityLabel(priority) { return { daily: ['当日完成', 'daily'], weekly: ['本周完成', 'weekly'], longterm: ['长期任务', 'longterm'] }[priority] || ['本周完成', 'weekly'] }
  function reviewTagBadges(task) { return (task.tags || []).map((tag) => tag === 'test' ? '<span class="badge review-tag test">🧪 测试</span>' : '<span class="badge review-tag optimization">◆ 关键优化</span>').join('') }
  function statusOptions(current) { return [['todo', '待办'], ['doing', '进行中'], ['waiting', '已完成待客户回复'], ['done', '已完成']].map(([value, label]) => `<option value="${value}"${value === current ? ' selected' : ''}>${label}</option>`).join('') }
  function taskCard(task) { const info = urgencyInfo(task); const [priorityText, priorityClass] = priorityLabel(task.priority); const check = task.status === 'done' ? '✓' : task.status === 'waiting' ? '…' : task.status === 'doing' ? '–' : ''; const nextStatus = { todo: 'doing', doing: 'waiting', waiting: 'done', done: 'todo' }[task.status]; const nextText = { todo: '标记为进行中', doing: '标记为待客户回复', waiting: '标记为已完成', done: '恢复为待办' }[task.status]; const sortLabels = ['逾期任务', '本周任务自动晋级', '当日任务', '本周任务', '长期任务']; return `<article class="task-card ${task.status} priority-${task.priority}" data-task-id="${escapeHtml(task.id)}"><button class="task-check" type="button" data-action="status" title="${nextText}" aria-label="${nextText}">${check}</button><div class="task-content"><h3 class="task-title">${escapeHtml(task.title)}</h3>${task.notes ? `<p class="task-notes">${escapeHtml(task.notes)}</p>` : ''}<div class="task-meta"><select class="task-status-select status-${task.status}" data-action="set-status" aria-label="修改任务状态">${statusOptions(task.status)}</select><span class="priority-label ${priorityClass}">${priorityText}</span>${reviewTagBadges(task)}${deadlineBadge(task)}${promotionBadge(task)}${waitingBadge(task)}${staleBadge(task)}${task.pomodoroCount ? `<span class="badge focus">◉ ${task.pomodoroCount} 番茄 · ${task.focusMinutes} 分钟</span>` : ''}</div></div><div class="task-actions"><button class="task-action" type="button" data-action="edit" title="编辑" aria-label="编辑任务">✎</button><button class="task-action delete" type="button" data-action="delete" title="删除任务" aria-label="删除任务">×</button></div><span class="urgency-score">排序：${sortLabels[smartSortRank(task, info)]}</span></article>` }
  function renderTasks() { const list = $('#taskList'); const completed = state.tasks.filter((task) => task.status === 'done').sort((a, b) => new Date(b.doneAt || b.createdAt) - new Date(a.doneAt || a.createdAt)); const visible = state.filter === 'done' ? completed : visibleTasks(); list.innerHTML = visible.length ? visible.map(taskCard).join('') : `<div class="empty-state"><strong>${state.filter === 'all' ? '今天还没有安排任务' : '这个筛选下暂无任务'}</strong><p>${state.filter === 'all' ? '把脑中的下一件事写下来，给它一个清晰的起点。' : '切换其他筛选，或新建一项任务。'}</p></div>`; $('#completedList').innerHTML = completed.map(taskCard).join(''); $('#completedSummaryCount').textContent = completed.length; $('#completedSection').hidden = state.filter === 'done' }
  function renderStats() { const active = state.tasks.filter((task) => task.status !== 'done'); const infos = active.map(urgencyInfo); $('#todoCount').textContent = state.tasks.filter((task) => task.status === 'todo').length; $('#overdueCount').textContent = infos.filter((info) => info.daysLeft !== null && info.daysLeft < 0).length; $('#staleCount').textContent = infos.filter((info) => info.ageDays > 7).length; $('#allCount').textContent = active.length; $('#todoTabCount').textContent = state.tasks.filter((task) => task.status === 'todo').length; $('#doingCount').textContent = state.tasks.filter((task) => task.status === 'doing').length; $('#waitingCount').textContent = state.tasks.filter((task) => task.status === 'waiting').length; $('#doneCount').textContent = state.tasks.filter((task) => task.status === 'done').length; const todayLogs = todayPomodoros(); $('#todayFocusCount').textContent = todayLogs.length; $('#todayFocusMinutes').textContent = todayLogs.reduce((sum, log) => sum + Number(log.minutes || 0), 0) }
  function renderFocusTaskOptions() { const select = $('#focusTaskSelect'); const current = select.value || timer.boundTaskId; const options = state.tasks.filter((task) => task.status !== 'done').sort(taskComparator); select.innerHTML = `<option value="">不绑定任务</option>${options.map((task) => `<option value="${escapeHtml(task.id)}">${escapeHtml(task.title)}</option>`).join('')}`; select.value = options.some((task) => task.id === current) ? current : '' }
  function todayPomodoros() { const start = todayDate().getTime(); return state.pomodoroLog.filter((log) => new Date(log.endedAt).getTime() >= start) }
  function renderFocusSummary() { const logs = todayPomodoros(); const byTask = new Map(); logs.forEach((log) => { const key = log.taskId || 'unbound'; const item = byTask.get(key) || { title: log.taskTitle || '未绑定任务', minutes: 0, count: 0 }; item.minutes += Number(log.minutes) || 0; item.count += 1; byTask.set(key, item) }); $('#summaryPomodoros').textContent = logs.length; $('#summaryMinutes').textContent = logs.reduce((sum, log) => sum + Number(log.minutes || 0), 0); const ranking = [...byTask.values()].sort((a, b) => b.minutes - a.minutes).slice(0, 5); $('#focusRanking').innerHTML = ranking.length ? ranking.map((item) => `<div class="focus-ranking-row"><span>${escapeHtml(item.title)}</span><strong>${item.minutes} 分钟</strong></div>`).join('') : '<p class="empty-inline">完成一个番茄后，这里会显示任务排行。</p>' }
  function setSyncStatus(status, message = '') { state.sync.status = status; state.sync.message = message; const el = $('#syncStatus'); el.className = `sync-status ${status}`; const labels = { local: '仅本地保存', pending: '等待同步', syncing: '正在同步…', synced: message || '已同步', offline: message || '离线 / 未同步', error: message || '同步失败' }; el.querySelector('.sync-label').textContent = labels[status] || status; $('#retrySyncButton').hidden = !['offline', 'error'].includes(status) }
  function render() { const now = new Date(); $('#todayLabel').textContent = now.toLocaleDateString('zh-CN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }); $('#sortSelect').value = state.sort; $('#focusLengthLabel').textContent = state.settings.focusMinutes; $('#breakLengthLabel').textContent = state.settings.shortBreakMinutes; renderTasks(); renderStats(); renderFocusTaskOptions(); renderFocusSummary(); updateTimerDisplay(); setSyncStatus(state.sync.status, state.sync.message) }

  function openTaskDialog(task = null) { $('#editingTaskId').value = task?.id || ''; $('#taskDialogEyebrow').textContent = task ? 'EDIT TASK' : 'NEW TASK'; $('#taskDialogTitle').textContent = task ? '编辑任务' : '新建任务'; $('#taskTitle').value = task?.title || ''; $('#taskPriority').value = task?.status === 'waiting' ? 'waiting' : (task?.priority || 'weekly'); $('#taskDeadline').value = task?.deadline || ''; $('#taskNotes').value = task?.notes || ''; $('#taskTagTest').checked = Boolean(task?.tags?.includes('test')); $('#taskTagOptimization').checked = Boolean(task?.tags?.includes('optimization')); $('#taskDialog').showModal(); setTimeout(() => $('#taskTitle').focus(), 20) }
  function closeTaskDialog() { $('#taskDialog').close() }
  function selectedReviewTags() { return [['test', '#taskTagTest'], ['optimization', '#taskTagOptimization']].filter(([, selector]) => $(selector).checked).map(([tag]) => tag) }
  function handleTaskSubmit(event) { event.preventDefault(); const title = $('#taskTitle').value.trim(); if (!title) return; const id = $('#editingTaskId').value; const existing = state.tasks.find((task) => task.id === id); const urgency = $('#taskPriority').value; const isWaiting = urgency === 'waiting'; const nextPriority = isWaiting ? (existing?.priority && existing.priority !== 'waiting' ? existing.priority : 'weekly') : urgency; if (existing) { const previousStatus = existing.status; existing.title = title; existing.priority = nextPriority; existing.deadline = $('#taskDeadline').value; existing.notes = $('#taskNotes').value.trim(); existing.tags = selectedReviewTags(); if (isWaiting && previousStatus !== 'waiting') { existing.status = 'waiting'; existing.waitingAt = new Date().toISOString(); delete existing.doneAt } else if (!isWaiting && previousStatus === 'waiting') { existing.status = 'todo'; delete existing.waitingAt; delete existing.doneAt } showToast('任务已更新', 'success') } else { state.tasks.push(normalizeTask({ id: safeId(), title, priority: nextPriority, deadline: $('#taskDeadline').value, notes: $('#taskNotes').value.trim(), status: isWaiting ? 'waiting' : 'todo', waitingAt: isWaiting ? new Date().toISOString() : undefined, createdAt: new Date().toISOString(), pomodoroCount: 0, focusMinutes: 0, tags: selectedReviewTags() })); showToast('任务已创建', 'success') } closeTaskDialog(); persist() }
  function setTaskStatus(task, nextStatus) { if (!['todo', 'doing', 'waiting', 'done'].includes(nextStatus) || task.status === nextStatus) return; const previousStatus = task.status; task.status = nextStatus; if (nextStatus === 'waiting' && previousStatus !== 'waiting') task.waitingAt = new Date().toISOString(); else if (nextStatus !== 'waiting') delete task.waitingAt; if (nextStatus === 'done') task.doneAt = new Date().toISOString(); else delete task.doneAt; persist(); const messages = { todo: '任务已恢复为待办', doing: '任务已进入进行中', waiting: '工作已完成，正在等待客户回复', done: '任务已完成，做得好。' }; showToast(messages[nextStatus], 'success') }
  function cycleTaskStatus(task) { const nextStatus = { todo: 'doing', doing: 'waiting', waiting: 'done', done: 'todo' }[task.status]; setTaskStatus(task, nextStatus) }
  function handleStatusSelect(event) { const select = event.target.closest('[data-action="set-status"]'); if (!select) return; const card = select.closest('[data-task-id]'); const task = state.tasks.find((item) => item.id === card?.dataset.taskId); if (task) setTaskStatus(task, select.value) }
  function handleTaskAction(event) { const button = event.target.closest('[data-action]'); if (!button) return; const card = button.closest('[data-task-id]'); const task = state.tasks.find((item) => item.id === card?.dataset.taskId); if (!task) return; if (button.dataset.action === 'status') cycleTaskStatus(task); if (button.dataset.action === 'edit') openTaskDialog(task); if (button.dataset.action === 'delete' && confirm(`确定删除“${task.title}”吗？此操作无法撤销。`)) { state.tasks = state.tasks.filter((item) => item.id !== task.id); persist(); showToast('任务已删除', 'success') } }

  function scheduleSync() { if (!state.sync.token || !state.sync.gistId) { setSyncStatus('local'); return } localStorage.setItem(STORAGE.pending, new Date().toISOString()); setSyncStatus('pending'); clearTimeout(syncTimer); syncTimer = setTimeout(syncToCloud, 900) }
  function apiHeaders() { return { Authorization: `Bearer ${state.sync.token}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' } }
  async function responseError(response) { let detail = ''; try { const body = await response.json(); detail = body.message || '' } catch (_) {} const messages = { 401: 'Token 无效或已过期，请在设置中更新。', 403: 'GitHub 拒绝了请求，可能是 Token 没有 gist 权限或触发了限流。', 404: '找不到这个 Gist，请检查 Gist ID。', 422: 'Gist 数据格式不正确，无法保存。' }; return messages[response.status] || `${response.status}：${detail || 'GitHub 请求失败'}` }
  function cloudPayload() { return { files: { 'tasks.json': { content: JSON.stringify(state.tasks, null, 2) }, 'pomodoro-log.json': { content: JSON.stringify(state.pomodoroLog, null, 2) } } } }
  async function createGist() { const response = await fetch('https://api.github.com/gists', { method: 'POST', headers: apiHeaders(), body: JSON.stringify({ description: 'Daily Planner data', public: false, ...cloudPayload() }) }); if (!response.ok) throw new Error(await responseError(response)); const data = await response.json(); state.sync.gistId = data.id; saveLocal(); $('#gistIdInput').value = data.id; showToast(`已创建 Secret Gist：${data.id}`, 'success'); return data }
  async function syncFromCloud({ silent = false } = {}) { if (!state.sync.token) { setSyncStatus('local'); if (!silent) showToast('请先在设置中填写 GitHub Token。', 'warning'); return } setSyncStatus('syncing'); try { let data; if (!state.sync.gistId) data = await createGist(); else { const response = await fetch(`https://api.github.com/gists/${encodeURIComponent(state.sync.gistId)}`, { headers: apiHeaders() }); if (!response.ok) throw new Error(await responseError(response)); data = await response.json() } const tasksFile = data.files?.['tasks.json']?.content; const logsFile = data.files?.['pomodoro-log.json']?.content; if (tasksFile) state.tasks = JSON.parse(tasksFile).map(normalizeTask); if (logsFile) state.pomodoroLog = JSON.parse(logsFile); localStorage.removeItem(STORAGE.pending); saveCloudCache(); saveLocal(); setSyncStatus('synced', `已同步 ${new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}`); render(); if (!silent) showToast('已读取云端数据', 'success') } catch (error) { setSyncStatus(navigator.onLine ? 'error' : 'offline', error.message); if (!silent) showToast(error.message, 'error') } }
  async function syncToCloud() { if (!state.sync.token || !state.sync.gistId) { setSyncStatus('local'); return } setSyncStatus('syncing'); try { const response = await fetch(`https://api.github.com/gists/${encodeURIComponent(state.sync.gistId)}`, { method: 'PATCH', headers: apiHeaders(), body: JSON.stringify(cloudPayload()) }); if (!response.ok) throw new Error(await responseError(response)); localStorage.removeItem(STORAGE.pending); saveCloudCache(); setSyncStatus('synced', `已同步 ${new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}`) } catch (error) { setSyncStatus(navigator.onLine ? 'error' : 'offline', error.message); showToast(`${error.message} 已保留本地修改。`, 'error') } }

  function timerDuration(phase) { return (phase === 'focus' ? state.settings.focusMinutes : (timer.completedFocuses % state.settings.longBreakInterval === 0 && timer.completedFocuses > 0 ? state.settings.longBreakMinutes : state.settings.shortBreakMinutes)) * 60 }
  function startTimer() { if (timer.running) { timer.running = false; clearInterval(timer.interval); $('#timerStartButton').innerHTML = '<span>▶</span> 继续'; renderTimerState(); return } if (!timer.remaining || timer.remaining <= 0) { timer.phase = 'focus'; timer.remaining = timerDuration('focus'); timer.total = timer.remaining; timer.startedAt = new Date().toISOString() } timer.running = true; timer.interval = setInterval(() => { timer.remaining -= 1; updateTimerDisplay(); if (timer.remaining <= 0) completeTimerPhase() }, 1000); renderTimerState() }
  function resetTimer() { timer.running = false; clearInterval(timer.interval); timer.phase = 'focus'; timer.remaining = timerDuration('focus'); timer.total = timer.remaining; timer.startedAt = null; renderTimerState() }
  function endTimerEarly() { if (!timer.running && !timer.startedAt) return; timer.running = false; clearInterval(timer.interval); timer.remaining = 0; timer.startedAt = null; renderTimerState(); showToast('当前阶段已提前结束，未计入番茄。', 'warning') }
  function completeTimerPhase() { clearInterval(timer.interval); timer.running = false; const completedPhase = timer.phase; if (completedPhase === 'focus') { timer.completedFocuses += 1; const task = state.tasks.find((item) => item.id === timer.boundTaskId); const minutes = state.settings.focusMinutes; const endedAt = new Date().toISOString(); if (task) { task.pomodoroCount += 1; task.focusMinutes += minutes } state.pomodoroLog.push({ id: safeId(), taskId: task?.id || null, startedAt: timer.startedAt || new Date(Date.now() - minutes * 60000).toISOString(), endedAt, minutes, taskTitle: task?.title || '未绑定任务' }); persist(); notifyUser('专注完成', task ? `“${task.title}”完成一个番茄。` : '完成一个番茄。'); showToast('专注完成，休息一下吧。', 'success'); timer.phase = 'break' } else { notifyUser('休息结束', '准备开始下一个专注时段。'); showToast('休息结束，准备开始专注。', 'success'); timer.phase = 'focus' } timer.remaining = timerDuration(timer.phase); timer.total = timer.remaining; timer.startedAt = timer.phase === 'focus' ? new Date().toISOString() : null; renderTimerState() }
  function notifyUser(title, body) { if ('Notification' in window && Notification.permission === 'granted') new Notification(title, { body }); try { const audio = new (window.AudioContext || window.webkitAudioContext)(); const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.frequency.value = 740; oscillator.connect(gain); gain.connect(audio.destination); gain.gain.setValueAtTime(.0001, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.12, audio.currentTime + .02); gain.gain.exponentialRampToValueAtTime(.0001, audio.currentTime + .38); oscillator.start(); oscillator.stop(audio.currentTime + .4) } catch (_) {} }
  function updateTimerDisplay() { const seconds = Math.max(0, timer.remaining || timerDuration(timer.phase)); const minutes = Math.floor(seconds / 60); const rest = seconds % 60; $('#timerDisplay').textContent = `${String(minutes).padStart(2, '0')}:${String(rest).padStart(2, '0')}`; $('#timerDisplay').classList.toggle('breaking', timer.phase === 'break'); $('#timerProgressBar').style.width = `${timer.total ? Math.min(100, Math.max(0, ((timer.total - seconds) / timer.total) * 100)) : 0}%`; $('#timerPhase').textContent = timer.running ? (timer.phase === 'focus' ? '专注进行中' : '休息进行中') : (timer.phase === 'break' ? '休息时间' : '准备开始'); $('#timerPhase').style.color = timer.phase === 'break' ? 'var(--orange)' : 'var(--green)' }
  function renderTimerState() { $('#timerStartButton').innerHTML = timer.running ? '<span>Ⅱ</span> 暂停' : `<span>▶</span> ${timer.startedAt ? '继续' : '开始专注'}`; $('#timerResetButton').disabled = timer.running; $('#timerEndButton').hidden = !timer.startedAt; $('#pomodoroPanel').classList.toggle('timer-running', timer.running); updateTimerDisplay() }

  function readSettingsIntoForm() { $('#tokenInput').value = state.sync.token; $('#gistIdInput').value = state.sync.gistId; $('#focusMinutesInput').value = state.settings.focusMinutes; $('#shortBreakInput').value = state.settings.shortBreakMinutes; $('#longBreakInput').value = state.settings.longBreakMinutes; $('#longBreakIntervalInput').value = state.settings.longBreakInterval; $('#notificationButton').textContent = ('Notification' in window && Notification.permission === 'granted') ? '已允许桌面通知' : '请求通知权限' }
  function saveSettings(event) { if (event.submitter?.value === 'cancel') return; event.preventDefault(); state.sync.token = $('#tokenInput').value.trim(); state.sync.gistId = $('#gistIdInput').value.trim(); state.settings = { focusMinutes: clamp($('#focusMinutesInput').value, 1, 120, 25), shortBreakMinutes: clamp($('#shortBreakInput').value, 1, 60, 5), longBreakMinutes: clamp($('#longBreakInput').value, 1, 90, 15), longBreakInterval: clamp($('#longBreakIntervalInput').value, 1, 12, 4) }; saveLocal(); if (!timer.running) resetTimer(); $('#settingsDialog').close(); render(); if (state.sync.token) syncFromCloud({ silent: true }); else setSyncStatus('local'); showToast('设置已保存', 'success') }
  function clamp(value, min, max, fallback) { const number = Number(value); return Number.isFinite(number) ? Math.min(max, Math.max(min, Math.round(number))) : fallback }
  function clearCredentials() { if (!confirm('清除本地 Token 和 Gist ID？云端数据不会被删除。')) return; state.sync.token = ''; state.sync.gistId = ''; saveLocal(); readSettingsIntoForm(); setSyncStatus('local'); showToast('本地凭证已清除', 'success') }
  function requestNotifications() { if (!('Notification' in window)) { showToast('当前浏览器不支持桌面通知。', 'warning'); return } Notification.requestPermission().then((permission) => { $('#notificationButton').textContent = permission === 'granted' ? '已允许桌面通知' : '未允许通知'; showToast(permission === 'granted' ? '桌面通知已开启' : '通知权限未开启', permission === 'granted' ? 'success' : 'warning') }) }

  function bindEvents() { $('#newTaskButton').addEventListener('click', () => openTaskDialog()); $('#closeTaskDialogButton').addEventListener('click', closeTaskDialog); $('#cancelTaskDialogButton').addEventListener('click', closeTaskDialog); $('#taskForm').addEventListener('submit', handleTaskSubmit); $('#taskList').addEventListener('click', handleTaskAction); $('#taskList').addEventListener('change', handleStatusSelect); $('#completedList').addEventListener('click', handleTaskAction); $('#completedList').addEventListener('change', handleStatusSelect); $$('.tab').forEach((tab) => tab.addEventListener('click', () => { state.filter = tab.dataset.filter; $$('.tab').forEach((item) => { const active = item === tab; item.classList.toggle('active', active); item.setAttribute('aria-selected', active) }); renderTasks() })); $('#sortSelect').addEventListener('change', (event) => { state.sort = event.target.value; renderTasks(); renderFocusTaskOptions() }); $('#settingsButton').addEventListener('click', () => { readSettingsIntoForm(); $('#settingsDialog').showModal() }); $('#settingsForm').addEventListener('submit', saveSettings); $('#clearCredentialsButton').addEventListener('click', clearCredentials); $('#syncNowButton').addEventListener('click', () => syncFromCloud()); $('#retrySyncButton').addEventListener('click', () => syncToCloud()); $('#notificationButton').addEventListener('click', requestNotifications); $('#collapsePomodoroButton').addEventListener('click', () => { const body = $('#timerBody'); const hidden = body.hidden; body.hidden = !hidden; $('#collapsePomodoroButton').textContent = hidden ? '⌃' : '⌄' }); $('#focusTaskSelect').addEventListener('change', (event) => { timer.boundTaskId = event.target.value }); $('#timerStartButton').addEventListener('click', startTimer); $('#timerResetButton').addEventListener('click', resetTimer); $('#timerEndButton').addEventListener('click', endTimerEarly); window.addEventListener('online', () => { if (state.sync.token && state.sync.gistId) syncToCloud() }); window.addEventListener('offline', () => setSyncStatus('offline', '离线 / 未同步')) }
  loadState(); bindEvents(); timer.remaining = timerDuration('focus'); timer.total = timer.remaining; render(); if (state.sync.token && state.sync.gistId && navigator.onLine) { if (localStorage.getItem(STORAGE.pending)) syncToCloud(); else syncFromCloud({ silent: true }) }
})()
